# This is a GitHub Actions workflow file.
# To use it, create a file named 'ruff-autofix.yml' in the '.github/workflows/' directory of your repository.
# This workflow will automatically run Ruff to lint and fix your Python code on every push or pull request to the main branch.

name: 'Ruff Auto-Fixer'

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ruff-fix:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository's code so the workflow can access it.
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up the specific version of Python your project uses.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # You can change this to your project's Python version

      # Step 3: Install your project's dependencies, including Ruff.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          # Installs dependencies from your requirements.txt file if it exists
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi

      # Step 4: Run Ruff with the --fix and --unsafe-fixes flags.
      # The --exit-zero flag ensures that the workflow step doesn't fail if Ruff finds issues,
      # allowing the subsequent commit step to run.
      - name: Run Ruff with auto-fix
        run: |
          ruff check backend/ --fix --unsafe-fixes --exit-zero

      # Step 5: Commit any changes made by Ruff back to the repository.
      # This action automatically detects if files were changed and creates a commit.
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Apply automated Ruff fixes"
          # This ensures the commit is made to the correct branch in a pull request
          branch: ${{ github.head_ref }}
          commit_options: '--no-verify'
          repository: .
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions-bot@users.noreply.github.com"
          commit_author: "GitHub Actions Bot <github-actions-bot@users.noreply.github.com>"

